# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Herashop', '0004_auto_20170122_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='lon',
            new_name='lng',
        ),
    ]
